### ISSUE TITLE
No library named Valorant

### ISSUE THREAD

**Issue by vodelYT** [frissyn/valorant.py#11]
whatever i try i cannot install the valorant library
`~/ValorantBot$ pip install valorant.py
ERROR: Could not find a version that satisfies the requirement valorant.py (from versions: none)
ERROR: No matching distribution found for valorant.py
WARNING: You are using pip version 19.3.1; however, version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
~/ValorantBot$ pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/fe/ef/60d7ba03b5c442309ef42e7d69959f73aacccd0d86008362a681c4698e83/pip-21.0.1-py3-none-any.whl (1.5MB)
     |████████████████████████████████| 1.5MB 3.4MB/s 
ERROR: dephell 0.8.3 has requirement pip<=19.3.1,>=18.0, but you'll have pip 21.0.1 which is incompatible.
Installing collected packages: pip
  Found existing installation: pip 19.3.1
    Uninstalling pip-19.3.1:
      Successfully uninstalled pip-19.3.1
Successfully installed pip-21.0.1
~/ValorantBot$ pip install valorant.py
ERROR: Could not find a version that satisfies the requirement valorant.py
ERROR: No matching distribution found for valorant.py
~/ValorantBot$ python -m poetry add valorant.py

[ValueError]
Could not find a matching version of package valorant.py
~/ValorantBot$ easy_install valorant.py
WARNING: The easy_install command is deprecated and will be removed in a future version.
Searching for valorant.py
Reading https://pypi.org/simple/valorant.py/
Couldn't find index page for 'valorant.py' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for valorant.py
error: Could not find suitable distribution for Requirement.parse('valorant.py')`

**Comment by vodelYT** [comment]
PS:
i just used
pip install git+https://github.com/frissyn/valorant.py
and it works fine

**Comment by frissyn** [comment]
@vodelYT for future reference, the package is listed on PyPI as `valorant`, not `valorant.py`. Sorry if that caused any confusion!
