### ISSUE TITLE
Valorant Rank

### ISSUE THREAD

**Issue by vodelYT** [frissyn/valorant.py#12]
Is there a way to get the current Competitive Rank of a Player and or their Points?
I can't find a way.

**Comment by frissyn** [comment]
@vodelYT There currently isn't a way to do that, sorry! I'm still working on covering that, but I'm maintaining a lot of projects right now, so it's hard. This is on my to-do list though!

**Comment by vodelYT** [comment]
Alright, looks like i need to scrape the web on a tracking website
