### ISSUE TITLE
ValueError: The given locale 'en-AE' is invalid. See `valorant.values.LOCALES` for a list of valid locales.

### ISSUE THREAD

**Issue by EjinJS** [frissyn/valorant.py#21]

**Comment by EjinJS** [comment]
is this problem with module or error in my code , I just copied the example and replaced the API key with mine

**Comment by frissyn** [comment]
Looks like Riot has added some new regions! This is a problem with the module, I'll fix ASAP, thanks for the issue.

**Comment by frissyn** [comment]
@EjinJS @Willmidd1 Are you guys passing your own locales to the client like `valorant.Client(key, locale="en-AE")` or are you just passing a key. Because both of those raise different problems that need different solutions.

**Comment by frissyn** [comment]
`en-AE` is not a valid region locale at all. If it's being set automatically then that's a problem that can be solved passing your own locale (a valid one, of course). The closest valid locales to `en-AE` are `en-AU` and `ar-AE`.
