### ISSUE TITLE
Local Client Error.

### ISSUE THREAD

**Issue by bboychris168** [frissyn/valorant.py#23]
I'm currently getting an error when running your local client example.

AttributeError: partially initialized module 'valorant has no attribute 'LocalClient' (most likely due to a circular import)

Would you perhaps know what is currently causing this error? I have installed the package through pip install Valorant line.

**Comment by frissyn** [comment]
@bboychris168 Sorry for the late response, I probably shipped a bug with the last update, I'll put out a hotfix later on today, thanks for reporting!

**Comment by frissyn** [comment]
@bboychris168 

Can you provide more context on the issue you ran into? I can't recreate the error on my machine with a fresh installation of the package, everything is working fine. It could be an issue on your end if I'm not missing anything.
