### ISSUE TITLE
Question on API: Personal API Key request

### ISSUE THREAD

**Issue by agrenier-gnss** [frissyn/valorant.py#43]
Hi everyone,

The question is a bit off this library. I am looking into making a personal app for tracking my progress in Valorant. Online trackers I could find do not give me all the stats I want, so I want to make my own in Python.

I understand the development API key does not give me access to match history. I suppose I should request for a Personal API key, but Valorant cannot be selected in the Product Game focus section. 

I was wondering if any of you tried this before and would have a solution for this. I really don't want to log all my stats manually ... 

Thanks for your help.

**Comment by brain-d3d** [comment]
valorants only for production rn, just make a website with google sites and do the application
you probably will get it

**Comment by frissyn** [comment]
@agrenier-gnss VALORANT Production API access doesn't include personal apps at the moment, but you could still explain your use case in the application description and take the chance it'll be accepted. There have been personal apps that deal with match/performance statistics that the team has accepted before.
